-- SF6 Tekken Mode PROBE: checks every row of sheets/hooks.json against the running game.
-- GENERATED by tools/build.py. Do not edit; change the sheets or src/probe.lua.tpl.
-- Use: start an offline match, open the REFramework menu (Insert), find "SF6 Tekken Probe", press the button.
-- It writes reframework/data/sf6_tekken/probe_report.json. Send that file back so the hook sheet can be marked verified.

local HOOKS = {
  {
    ["id"] = "round_no",
    ["kind"] = "field",
    ["path_steps"] = {
      "Round",
      "RoundNo"
    },
    ["access"] = "r",
    ["value_type"] = "int",
    ["purpose"] = "Detect a new round so per-round state resets",
    ["source"] = "SF6_replay_capture: gBattle.Round.RoundNo",
    ["verified"] = false
  },
  {
    ["id"] = "stage_timer",
    ["kind"] = "field",
    ["path_steps"] = {
      "Game",
      "stage_timer"
    },
    ["access"] = "r",
    ["value_type"] = "int",
    ["purpose"] = "Detect that the match simulation advanced one tick (render frames and sim ticks differ)",
    ["source"] = "SF6_replay_capture: gBattle.Game.stage_timer",
    ["verified"] = false
  },
  {
    ["id"] = "hp_now",
    ["kind"] = "field",
    ["path_steps"] = {
      "Player",
      "mcPlayer",
      "[i]",
      "vital_new"
    },
    ["access"] = "rw",
    ["value_type"] = "int",
    ["purpose"] = "Read health to find damage taken and Rage threshold; write it to add bonus damage and chip damage",
    ["source"] = "SF6_replay_capture: cPlayer[i].vital_new (read only there; writing is unproven)",
    ["verified"] = false
  },
  {
    ["id"] = "guard_time",
    ["kind"] = "field",
    ["path_steps"] = {
      "Player",
      "mcPlayer",
      "[i]",
      "guard_time"
    },
    ["access"] = "r",
    ["value_type"] = "int",
    ["purpose"] = "Detect the moment a fighter starts blocking (blockstun begins) for Heat chip damage",
    ["source"] = "SF6_replay_capture: cPlayer[i].guard_time",
    ["verified"] = false
  },
  {
    ["id"] = "juggle_counter",
    ["kind"] = "field",
    ["path_steps"] = {
      "Player",
      "mcPlayer",
      "[i]",
      "combo_dm_air"
    },
    ["access"] = "r",
    ["value_type"] = "int",
    ["purpose"] = "Research only: what SF6 tracks during air combos, to see whether juggle scaling can be changed",
    ["source"] = "SF6_replay_capture: cPlayer[i].combo_dm_air (meaning not confirmed)",
    ["verified"] = false
  },
  {
    ["id"] = "key_state",
    ["kind"] = "api",
    ["path_steps"] = {
      "reframework",
      "is_key_down"
    },
    ["access"] = "r",
    ["value_type"] = "bool",
    ["purpose"] = "Read the keyboard keys that trigger Heat (REFramework gives raw keys only, no gamepad)",
    ["source"] = "Melty game_info for SF6: reframework:is_key_down(vk)",
    ["verified"] = false
  }
}

if re ~= nil and sdk ~= nil then
    local report_text = "not run yet"

    local function describe(v)
        local n = tonumber(v)
        if n ~= nil then return { type = "number", value = n } end
        return { type = type(v), value = tostring(v) }
    end

    local function walk(steps, i)
        local t = sdk.find_type_definition("gBattle")
        if not t then return false, "gBattle type not found" end
        local obj = t:get_field(steps[1]):get_data(nil)
        for s = 2, #steps do
            local key = steps[s]
            if key == "[i]" then key = i end
            if obj == nil then return false, "nil before " .. tostring(key) end
            obj = obj[key]
        end
        if obj == nil then return false, "nil at end of path" end
        return true, obj
    end

    local function field_names_of(obj)
        local names = {}
        local ok = pcall(function()
            local td = obj:get_type_definition()
            for _, f in ipairs(td:get_fields()) do names[#names + 1] = f:get_name() end
        end)
        if not ok then return { "(could not list fields)" } end
        return names
    end

    local function run_probe()
        local report = { results = {}, player_fields = {} }
        for _, hook in ipairs(HOOKS) do
            local entry = { id = hook.id, kind = hook.kind }
            if hook.kind == "api" then
                entry.ok = (reframework ~= nil and reframework.is_key_down ~= nil)
            else
                local per_player = {}
                local uses_player = false
                for _, step in ipairs(hook.path_steps) do
                    if step == "[i]" then uses_player = true end
                end
                local players = uses_player and { 0, 1 } or { 0 }
                local all_ok = true
                for _, i in ipairs(players) do
                    local ok, found, value = pcall(walk, hook.path_steps, i)
                    if ok and found == true then
                        per_player[#per_player + 1] = describe(value)
                    else
                        all_ok = false
                        per_player[#per_player + 1] = { error = tostring(ok and value or found) }
                    end
                end
                entry.ok = all_ok
                entry.reads = per_player
            end
            report.results[#report.results + 1] = entry
        end
        local okp, found, obj = pcall(walk, { "Player", "mcPlayer", "[i]" }, 0)
        if okp and found == true then report.player_fields = field_names_of(obj) end
        local saved = json.dump_file("sf6_tekken/probe_report.json", report)
        local bad = 0
        for _, e in ipairs(report.results) do if not e.ok then bad = bad + 1 end end
        report_text = string.format("%d hooks checked, %d failed. Saved: %s", #report.results, bad, tostring(saved))
    end

    re.on_draw_ui(function()
        if imgui.tree_node("SF6 Tekken Probe") then
            imgui.text("Press during an offline match.")
            if imgui.button("Run probe now") then
                local ok, err = pcall(run_probe)
                if not ok then report_text = "probe crashed: " .. tostring(err) end
            end
            imgui.text(report_text)
            imgui.tree_pop()
        end
    end)
end
