-- SF6 Tekken Mode: Rage and Heat for Street Fighter 6, OFFLINE play only.
-- GENERATED by tools/build.py from sheets/*.json. Do not edit this file: change the sheets or src/engine.lua.tpl.
-- Status: not yet run in the real game. Field names are unproven until sf6_tekken_probe.lua says otherwise.

local ROWS = {
  ["mechanics"] = {
    {
      ["id"] = "rage",
      ["enabled"] = true,
      ["kind"] = "rage",
      ["trigger"] = "hp_below",
      ["hp_threshold_pct"] = 25,
      ["damage_mult"] = 1.1,
      ["duration_ticks"] = "n/a",
      ["cooldown_ticks"] = "n/a",
      ["chip_pct_of_max"] = "n/a",
      ["uses_per_round"] = "n/a",
      ["pause_while_opponent_in_hitstun"] = "n/a",
      ["chip_can_ko"] = "n/a",
      ["recover_pct_of_max_per_landed_attack"] = "n/a",
      ["chip_taken_reduction_pct"] = 70,
      ["hit_trims_recoverable_pct"] = "n/a",
      ["heat_start_heals_pct_of_pool"] = "n/a",
      ["armed_ticks"] = "n/a",
      ["bonus_pct_of_max"] = "n/a",
      ["fx_speed_scale"] = "n/a",
      ["fx_frames"] = "n/a",
      ["fx_method"] = "n/a",
      ["boost_frames"] = "n/a",
      ["big_boost_frames"] = "n/a",
      ["key_p1"] = "n/a",
      ["key_p2"] = "n/a",
      ["uses_hooks"] = {
        "round_no",
        "stage_timer",
        "hp_now",
        "hp_max"
      },
      ["status"] = "implemented",
      ["verified"] = true,
      ["note"] = "Tekken 8 Rage: at or under 25% health (45 of 180), every hit deals 10% more damage (rounded down) and chip damage taken is cut by 70%. Not possible here: Rage Art. The earlier numbers (20%, +15%) were verified working in game; these new numbers are untested. User played the Tekken 8 version offline and reported 'it feels good now' (2026-10-07). That is a general confirmation: the individual readouts were not reviewed one by one."
    },
    {
      ["id"] = "heat",
      ["enabled"] = true,
      ["kind"] = "heat",
      ["trigger"] = "key",
      ["hp_threshold_pct"] = "n/a",
      ["damage_mult"] = 1.0,
      ["duration_ticks"] = 600,
      ["cooldown_ticks"] = "n/a",
      ["chip_pct_of_max"] = 2.0,
      ["uses_per_round"] = 1,
      ["pause_while_opponent_in_hitstun"] = true,
      ["chip_can_ko"] = false,
      ["recover_pct_of_max_per_landed_attack"] = 1.0,
      ["chip_taken_reduction_pct"] = "n/a",
      ["hit_trims_recoverable_pct"] = 30,
      ["heat_start_heals_pct_of_pool"] = 50,
      ["armed_ticks"] = "n/a",
      ["bonus_pct_of_max"] = "n/a",
      ["fx_speed_scale"] = "n/a",
      ["fx_frames"] = "n/a",
      ["fx_method"] = "n/a",
      ["boost_frames"] = "n/a",
      ["big_boost_frames"] = "n/a",
      ["key_p1"] = 112,
      ["key_p2"] = 113,
      ["uses_hooks"] = {
        "round_no",
        "stage_timer",
        "hp_now",
        "hp_max",
        "guard_time",
        "hitstun",
        "key_state",
        "button_state"
      },
      ["status"] = "implemented",
      ["verified"] = true,
      ["note"] = "Tekken 8 Heat: press the key (P1 F1 = 112, P2 F2 = 113) to start Heat. It can be used once per round and lasts 10 seconds of running time (600 match ticks, about 60 per second); the timer stops while the opponent is in hitstun. Heat gives no damage bonus. A blocked hit costs the blocker chip damage that cannot KO; it is recoverable and is won back when the chipped fighter lands attacks. Not possible here: Heat Smash, Heat Dash, Heat Burst (2+3) input and Engager moves. Earlier version (+15% damage, 20 second cooldown, permanent chip) was verified in game; this version is a redesign and is untested. User played the Tekken 8 version offline and reported 'it feels good now' (2026-10-07). That is a general confirmation: the individual readouts were not reviewed one by one."
    },
    {
      ["id"] = "heat_smash",
      ["enabled"] = true,
      ["kind"] = "heat_smash",
      ["trigger"] = "heat_key_while_in_heat",
      ["hp_threshold_pct"] = "n/a",
      ["damage_mult"] = "n/a",
      ["duration_ticks"] = "n/a",
      ["cooldown_ticks"] = "n/a",
      ["chip_pct_of_max"] = "n/a",
      ["uses_per_round"] = "n/a",
      ["pause_while_opponent_in_hitstun"] = "n/a",
      ["chip_can_ko"] = "n/a",
      ["recover_pct_of_max_per_landed_attack"] = "n/a",
      ["chip_taken_reduction_pct"] = "n/a",
      ["hit_trims_recoverable_pct"] = "n/a",
      ["heat_start_heals_pct_of_pool"] = "n/a",
      ["armed_ticks"] = 120,
      ["bonus_pct_of_max"] = 15,
      ["fx_speed_scale"] = "n/a",
      ["fx_frames"] = "n/a",
      ["fx_method"] = "n/a",
      ["boost_frames"] = "n/a",
      ["big_boost_frames"] = "n/a",
      ["key_p1"] = "n/a",
      ["key_p2"] = "n/a",
      ["uses_hooks"] = {
        "round_no",
        "stage_timer",
        "hp_now",
        "hp_max",
        "key_state"
      },
      ["status"] = "implemented",
      ["verified"] = true,
      ["note"] = "Heat Smash stand-in: press the Heat key again while Heat is running to arm it for 2 seconds. The next hit that lands deals extra damage (15% of max health) and uses up your remaining Heat. If it does not land in time, the Heat is spent anyway. A blocked attack does not use it up. Not the real move: no animation, no armor. User played the Tekken 8 version offline and reported 'it feels good now' (2026-10-07). That is a general confirmation: the individual readouts were not reviewed one by one."
    },
    {
      ["id"] = "rage_art",
      ["enabled"] = true,
      ["kind"] = "rage_art",
      ["trigger"] = "key_while_in_rage",
      ["hp_threshold_pct"] = "n/a",
      ["damage_mult"] = "n/a",
      ["duration_ticks"] = "n/a",
      ["cooldown_ticks"] = "n/a",
      ["chip_pct_of_max"] = "n/a",
      ["uses_per_round"] = 1,
      ["pause_while_opponent_in_hitstun"] = "n/a",
      ["chip_can_ko"] = "n/a",
      ["recover_pct_of_max_per_landed_attack"] = "n/a",
      ["chip_taken_reduction_pct"] = "n/a",
      ["hit_trims_recoverable_pct"] = "n/a",
      ["heat_start_heals_pct_of_pool"] = "n/a",
      ["armed_ticks"] = 120,
      ["bonus_pct_of_max"] = 18,
      ["fx_speed_scale"] = "n/a",
      ["fx_frames"] = "n/a",
      ["fx_method"] = "n/a",
      ["boost_frames"] = "n/a",
      ["big_boost_frames"] = "n/a",
      ["key_p1"] = 114,
      ["key_p2"] = 115,
      ["uses_hooks"] = {
        "round_no",
        "stage_timer",
        "hp_now",
        "hp_max",
        "key_state"
      },
      ["status"] = "implemented",
      ["verified"] = true,
      ["note"] = "Rage Art stand-in: while in Rage, press the key (P1 F3 = 114, P2 F4 = 115) to arm it for 2 seconds, once per round. The next hit that lands deals extra damage (18% of max health), removes the opponent's recoverable health, wins back some of yours, and ends your Rage. If it does not land in time, Rage still ends. Not the real move: no animation or cinematic. User played the Tekken 8 version offline and reported 'it feels good now' (2026-10-07). That is a general confirmation: the individual readouts were not reviewed one by one."
    },
    {
      ["id"] = "slowmo_fx",
      ["enabled"] = false,
      ["kind"] = "slowmo_fx",
      ["trigger"] = "smash_or_art_landed",
      ["hp_threshold_pct"] = "n/a",
      ["damage_mult"] = "n/a",
      ["duration_ticks"] = "n/a",
      ["cooldown_ticks"] = "n/a",
      ["chip_pct_of_max"] = "n/a",
      ["uses_per_round"] = "n/a",
      ["pause_while_opponent_in_hitstun"] = "n/a",
      ["chip_can_ko"] = "n/a",
      ["recover_pct_of_max_per_landed_attack"] = "n/a",
      ["chip_taken_reduction_pct"] = "n/a",
      ["hit_trims_recoverable_pct"] = "n/a",
      ["heat_start_heals_pct_of_pool"] = "n/a",
      ["armed_ticks"] = "n/a",
      ["bonus_pct_of_max"] = "n/a",
      ["fx_speed_scale"] = 0.5,
      ["fx_frames"] = 30,
      ["fx_method"] = "max_fps",
      ["boost_frames"] = "n/a",
      ["big_boost_frames"] = "n/a",
      ["key_p1"] = "n/a",
      ["key_p2"] = "n/a",
      ["uses_hooks"] = {
        "global_speed",
        "scene_time_scale",
        "max_fps"
      },
      ["status"] = "implemented",
      ["verified"] = false,
      ["note"] = "Experimental impact slow-motion: when a Heat Smash or Rage Art lands, slow the game to 50% for about half a second by lowering the frame cap (so it looks choppy). Off by default. Test 2026-10-07: global speed and scene time scale did not visibly slow SF6; the frame cap method did. Speed and length can be changed live in the panel."
    },
    {
      ["id"] = "hitstop_boost",
      ["enabled"] = true,
      ["kind"] = "hitstop_boost",
      ["trigger"] = "any_hit_landed",
      ["hp_threshold_pct"] = "n/a",
      ["damage_mult"] = "n/a",
      ["duration_ticks"] = "n/a",
      ["cooldown_ticks"] = "n/a",
      ["chip_pct_of_max"] = "n/a",
      ["uses_per_round"] = "n/a",
      ["pause_while_opponent_in_hitstun"] = "n/a",
      ["chip_can_ko"] = "n/a",
      ["recover_pct_of_max_per_landed_attack"] = "n/a",
      ["chip_taken_reduction_pct"] = "n/a",
      ["hit_trims_recoverable_pct"] = "n/a",
      ["heat_start_heals_pct_of_pool"] = "n/a",
      ["armed_ticks"] = "n/a",
      ["bonus_pct_of_max"] = "n/a",
      ["fx_speed_scale"] = "n/a",
      ["fx_frames"] = "n/a",
      ["fx_method"] = "n/a",
      ["boost_frames"] = 3,
      ["big_boost_frames"] = 10,
      ["key_p1"] = "n/a",
      ["key_p2"] = "n/a",
      ["uses_hooks"] = {
        "hit_stop"
      },
      ["status"] = "implemented",
      ["verified"] = true,
      ["note"] = "Weightier hits: when a hit lands, add 3 frames to the game's hit freeze counter on both fighters (10 frames when a Heat Smash or Rage Art lands). On by default: the user tried it offline and said it feels good (2026-10-07). Sizes can be changed live in the panel and are saved."
    }
  },
  ["hooks"] = {
    {
      ["id"] = "round_no",
      ["kind"] = "field",
      ["path_steps"] = {
        "Round",
        "RoundNo"
      },
      ["access"] = "r",
      ["value_type"] = "int",
      ["purpose"] = "Detect a new round so per-round state resets (not reliable alone: see evidence)",
      ["source"] = "SF6_replay_capture: gBattle.Round.RoundNo",
      ["read_verified"] = true,
      ["write_verified"] = "n/a",
      ["evidence"] = "Probe 2026-10-07: read 0. In-game panel showed 'round 0' in both round 1 and a later round, so it does not reliably change between rounds; the mod also resets when stage_timer jumps back by more than 30."
    },
    {
      ["id"] = "stage_timer",
      ["kind"] = "field",
      ["path_steps"] = {
        "Game",
        "stage_timer"
      },
      ["access"] = "r",
      ["value_type"] = "int",
      ["purpose"] = "Detect that the match simulation advanced one tick (render frames and sim ticks differ)",
      ["source"] = "SF6_replay_capture: gBattle.Game.stage_timer",
      ["read_verified"] = true,
      ["write_verified"] = "n/a",
      ["evidence"] = "Probe 2026-10-07: read 153"
    },
    {
      ["id"] = "hp_now",
      ["kind"] = "field",
      ["path_steps"] = {
        "Player",
        "mcPlayer",
        "[i]",
        "vital_new"
      },
      ["access"] = "rw",
      ["value_type"] = "int",
      ["purpose"] = "Read health to find damage taken and Rage threshold; write it to add bonus damage and chip damage",
      ["source"] = "SF6_replay_capture: cPlayer[i].vital_new (read only there; writing is unproven)",
      ["read_verified"] = true,
      ["write_verified"] = true,
      ["evidence"] = "Probe 2026-10-07: both players read 10000 then 9250/10000. Write test: wrote 8349 over 8350; value was still 8349 one frame later (not reverted). Later reads were lower (7749 at 30 frames, 6849 at 120) because P1 was taking damage, not a revert. A bonus write during a real hit is still to be seen."
    },
    {
      ["id"] = "guard_time",
      ["kind"] = "field",
      ["path_steps"] = {
        "Player",
        "mcPlayer",
        "[i]",
        "guard_time"
      },
      ["access"] = "r",
      ["value_type"] = "int",
      ["purpose"] = "Detect the moment a fighter starts blocking (blockstun begins) for Heat chip damage",
      ["source"] = "SF6_replay_capture: cPlayer[i].guard_time",
      ["read_verified"] = true,
      ["write_verified"] = "n/a",
      ["evidence"] = "Probe 2026-10-07: both players read 0 (not blocking). Value while blocking not seen yet."
    },
    {
      ["id"] = "juggle_counter",
      ["kind"] = "field",
      ["path_steps"] = {
        "Player",
        "mcPlayer",
        "[i]",
        "combo_dm_air"
      },
      ["access"] = "r",
      ["value_type"] = "int",
      ["purpose"] = "Research only: what SF6 tracks during air combos, to see whether juggle scaling can be changed",
      ["source"] = "SF6_replay_capture: cPlayer[i].combo_dm_air (meaning not confirmed)",
      ["read_verified"] = true,
      ["write_verified"] = "n/a",
      ["evidence"] = "Probe 2026-10-07: both players read -1 (no combo running). Meaning during a combo not seen yet."
    },
    {
      ["id"] = "key_state",
      ["kind"] = "api",
      ["path_steps"] = {
        "reframework",
        "is_key_down"
      },
      ["access"] = "r",
      ["value_type"] = "bool",
      ["purpose"] = "Read the keyboard keys that trigger Heat (REFramework gives raw keys only, no gamepad)",
      ["source"] = "Melty game_info for SF6: reframework:is_key_down(vk)",
      ["read_verified"] = true,
      ["write_verified"] = "n/a",
      ["evidence"] = "Probe 2026-10-07: reframework.is_key_down exists"
    },
    {
      ["id"] = "hp_max",
      ["kind"] = "field",
      ["path_steps"] = {
        "Player",
        "mcPlayer",
        "[i]",
        "vital_max"
      },
      ["access"] = "r",
      ["value_type"] = "int",
      ["purpose"] = "Real maximum health, for the Rage threshold and Heat chip size (replaces remembering the highest health seen)",
      ["source"] = "Probe 2026-10-07 field list: vital_max exists on the fighter object",
      ["read_verified"] = true,
      ["write_verified"] = "n/a",
      ["evidence"] = "Probe 2026-10-07: both players read 10000."
    },
    {
      ["id"] = "hitstun",
      ["kind"] = "field",
      ["path_steps"] = {
        "Player",
        "mcPlayer",
        "[i]",
        "damage_time"
      },
      ["access"] = "r",
      ["value_type"] = "int",
      ["purpose"] = "Tell when a fighter is in hitstun, so the opponent's Heat timer pauses while they are being hit (Tekken 8: the Heat timer stops while the opponent is hit)",
      ["source"] = "Fighter field list from the probe; SF6_replay_capture reads it as hitstun",
      ["read_verified"] = true,
      ["write_verified"] = "n/a",
      ["evidence"] = "Probe 2026-10-07: reads 0 for both fighters at rest. Its value during hitstun has not been seen yet."
    },
    {
      ["id"] = "button_state",
      ["kind"] = "field",
      ["path_steps"] = {
        "Player",
        "mcPlayer",
        "[i]",
        "pl_sw_now"
      },
      ["access"] = "r",
      ["value_type"] = "int",
      ["purpose"] = "The game's own held-button bits for each fighter, so Heat can later be started from a gamepad button combo (Tekken's Heat Burst is 2+3) instead of only a keyboard key",
      ["source"] = "Fighter field list from the probe; the meaning of the bits is not known yet",
      ["read_verified"] = true,
      ["write_verified"] = "n/a",
      ["evidence"] = "Probe 2026-10-07: reads 0 for both fighters with no buttons held. Which bit is which button is unknown."
    },
    {
      ["id"] = "global_speed",
      ["kind"] = "api",
      ["path_steps"] = {
        "via.Application",
        "set_GlobalSpeed"
      },
      ["access"] = "w",
      ["value_type"] = "float",
      ["purpose"] = "Slow the whole game briefly for dramatic moments (Heat Smash or Rage Art landing)",
      ["source"] = "A common REFramework pattern for RE Engine games; not seen working in SF6 yet",
      ["read_verified"] = "n/a",
      ["write_verified"] = false,
      ["evidence"] = "Probe 2026-10-07: the call is available. User test: it did not visibly slow the game."
    },
    {
      ["id"] = "sleep_time",
      ["kind"] = "field",
      ["path_steps"] = {
        "Player",
        "mcPlayer",
        "[i]",
        "sleep_time"
      },
      ["access"] = "r",
      ["value_type"] = "int",
      ["purpose"] = "Research: a candidate for the game's hit freeze, to make hits feel weightier",
      ["source"] = "Fighter field list from the probe; meaning unknown",
      ["read_verified"] = true,
      ["write_verified"] = "n/a",
      ["evidence"] = "Probe 2026-10-07: reads 0 for both fighters at rest. Behaviour during hits not seen."
    },
    {
      ["id"] = "damage_sleep",
      ["kind"] = "field",
      ["path_steps"] = {
        "Player",
        "mcPlayer",
        "[i]",
        "damage_sleep"
      },
      ["access"] = "r",
      ["value_type"] = "int",
      ["purpose"] = "Research: another candidate for the game's hit freeze",
      ["source"] = "Fighter field list from the probe; meaning unknown",
      ["read_verified"] = true,
      ["write_verified"] = "n/a",
      ["evidence"] = "Probe 2026-10-07: P1 read 0, P2 read 3 while a hit was fresh, so it moves around hits. Meaning (hit freeze?) not confirmed."
    },
    {
      ["id"] = "hit_stop",
      ["kind"] = "field",
      ["path_steps"] = {
        "Player",
        "mcPlayer",
        "[i]",
        "hit_stop"
      },
      ["access"] = "rw",
      ["value_type"] = "int",
      ["purpose"] = "The game's hit freeze counter (candidate): read to see it, and add a few frames to it on a landed hit so hits feel weightier",
      ["source"] = "SF6_replay_capture reads cPlayer[i].hit_stop",
      ["read_verified"] = true,
      ["write_verified"] = true,
      ["evidence"] = "Probe 2026-10-07: reads 0 for both fighters at rest. User test: with the hit freeze boost on, hits 'feel good' (general impression), so the game honours extra frames written to it. Exact behaviour was not checked value by value."
    },
    {
      ["id"] = "scene_time_scale",
      ["kind"] = "api",
      ["path_steps"] = {
        "via.SceneManager",
        "get_CurrentScene",
        "set_TimeScale"
      },
      ["access"] = "w",
      ["value_type"] = "float",
      ["purpose"] = "Second way to slow the game: the current scene's time scale",
      ["source"] = "A common REFramework pattern for RE Engine games; not seen working in SF6 yet",
      ["read_verified"] = "n/a",
      ["write_verified"] = false,
      ["evidence"] = "Probe 2026-10-07: the call is available. User test: it did not visibly slow the game."
    },
    {
      ["id"] = "max_fps",
      ["kind"] = "api",
      ["path_steps"] = {
        "via.Application",
        "set_MaxFps"
      },
      ["access"] = "w",
      ["value_type"] = "float",
      ["purpose"] = "Third way to slow the game: lower the frame cap, which slows anything that advances one step per frame; the original cap is restored afterwards",
      ["source"] = "A common REFramework pattern for RE Engine games; not seen working in SF6 yet",
      ["read_verified"] = "n/a",
      ["write_verified"] = true,
      ["evidence"] = "Probe 2026-10-07: reading the cap works. User test: this is the only method that visibly slowed the game, and the user was unsure how it felt (a lower frame rate looks choppy)."
    }
  }
}

local MECH = {}
for _, r in ipairs(ROWS.mechanics) do MECH[r.id] = r end

-- ---------------------------------------------------------------------------
-- Rules. Pure logic: takes a snapshot of the match, returns the health writes
-- to make. No game calls in here, so it can be tested without the game.
--   snap = { round = n, timer = n, hp = {[0]=n,[1]=n}, hp_max = {[0]=n,[1]=n} (optional), guard = {[0]=n,[1]=n}, hitstun = {[0]=n,[1]=n} (optional), keys = {[0]=bool,[1]=bool}, art_keys = {[0]=bool,[1]=bool} (optional) }
-- ---------------------------------------------------------------------------
local Engine = {}

local function new_player()
    return { max_hp = 0, last_hp = nil, last_guard = 0, rage = false, key_prev = false,
             heat_left = 0, heat_used = false, heat_paused = 0, heat_ran = 0, pool = 0,
             smash_left = 0, art_left = 0, art_used = false, rage_spent = false, key_prev_art = false }
end

function Engine.new_state()
    return { round = nil, last_timer = nil, tick = 0, chip_count = 0, smash_count = 0, art_count = 0, fx = nil, freeze = nil, last_event = "none yet", p = { [0] = new_player(), [1] = new_player() } }
end

local function enabled(id)
    local r = MECH[id]
    return r ~= nil and r.enabled == true
end

local function round_half_up(x)
    return math.floor(x + 0.5)
end

-- Debug switches for testing in the real game without having to get low on health or press the key.
Engine.debug = { force_rage = { [0] = false, [1] = false } }

-- Heat (Tekken 8): once per round, a timer that only runs while the opponent is not in hitstun.
function Engine.start_heat(st, i)
    local p = st.p[i]
    p.heat_left = MECH.heat.duration_ticks
    p.heat_used = true
    p.heat_paused = 0
    p.heat_ran = 0
end

-- Debug: arm the stand-in moves without the keys (ignores the usual conditions).
function Engine.arm_smash(st, i)
    if MECH.heat_smash then st.p[i].smash_left = MECH.heat_smash.armed_ticks end
end

function Engine.arm_art(st, i)
    if MECH.rage_art then
        st.p[i].art_left = MECH.rage_art.armed_ticks
        st.p[i].art_used = true
    end
end

function Engine.heat_active(st, i)
    return st.p[i].heat_left > 0
end

function Engine.heat_left(st, i)
    return st.p[i].heat_left
end

function Engine.heat_available(st, i)
    return not st.p[i].heat_used
end

-- Returns a table { [playerIndex] = newHealth } for every health write to make this call.
function Engine.step(st, snap)
    local writes = {}

    -- A new round: the game's round number changed, OR the match timer jumped backwards
    -- (probe screenshots showed the round number reading 0 in a later round, so it can't be relied on alone).
    local timer_jumped_back = st.last_timer ~= nil and snap.timer < st.last_timer - 30
    local was_heat = { [0] = Engine.heat_active(st, 0), [1] = Engine.heat_active(st, 1) }
    if snap.round ~= st.round or timer_jumped_back then
        for i = 0, 1 do
            if was_heat[i] then
                st.last_event = string.format("P%d Heat CLEARED by a reset: timer %s -> %s, round %s -> %s",
                    i + 1, tostring(st.last_timer), tostring(snap.timer), tostring(st.round), tostring(snap.round))
            end
        end
        st.round = snap.round
        st.last_timer = nil
        st.tick = 0
        st.p = { [0] = new_player(), [1] = new_player() }
    end

    if snap.timer == st.last_timer then return writes end
    st.last_timer = snap.timer
    st.tick = st.tick + 1

    -- Heat timer: runs only while the opponent is not in hitstun (when the sheet says so).
    if enabled("heat") then
        for i = 0, 1 do
            local p = st.p[i]
            if p.heat_left > 0 then
                local stunned = snap.hitstun ~= nil and (snap.hitstun[1 - i] or 0) > 0
                if MECH.heat.pause_while_opponent_in_hitstun and stunned then
                    p.heat_paused = p.heat_paused + 1
                else
                    p.heat_left = p.heat_left - 1
                    p.heat_ran = p.heat_ran + 1
                    if p.heat_left == 0 then
                        st.last_event = string.format("P%d Heat ended: timer ran out after %d running ticks (paused %d ticks while the opponent was hit)",
                            i + 1, p.heat_ran, p.heat_paused)
                    end
                end
            end
        end
    end

    -- Armed stand-in moves run out if nothing lands in time, and still cost you the Heat / Rage.
    for i = 0, 1 do
        local p = st.p[i]
        if p.smash_left > 0 then
            if not Engine.heat_active(st, i) then
                p.smash_left = 0
            else
                p.smash_left = p.smash_left - 1
                if p.smash_left == 0 then
                    p.heat_left = 0
                    st.last_event = string.format("P%d Heat Smash MISSED: Heat spent", i + 1)
                end
            end
        end
        if p.art_left > 0 then
            p.art_left = p.art_left - 1
            if p.art_left == 0 then
                p.rage_spent = true
                st.last_event = string.format("P%d Rage Art MISSED: Rage spent", i + 1)
            end
        end
    end

    local hp = { [0] = snap.hp[0], [1] = snap.hp[1] }
    for i = 0, 1 do
        local real_max = snap.hp_max ~= nil and snap.hp_max[i] or nil
        if real_max ~= nil and real_max > 0 then
            st.p[i].max_hp = real_max
        elseif hp[i] > st.p[i].max_hp then
            st.p[i].max_hp = hp[i]  -- fallback: highest health seen this round
        end
    end

    -- Heat: a key press starts it, once per round (a new round, or a timer reset, gives it back). Starting Heat wins back
    -- part of your recoverable health. Pressing the key again while in Heat arms the Heat Smash stand-in.
    if enabled("heat") then
        for i = 0, 1 do
            local p = st.p[i]
            local down = snap.keys[i] == true
            if down and not p.key_prev then
                if Engine.heat_active(st, i) then
                    if enabled("heat_smash") and p.smash_left == 0 then
                        p.smash_left = MECH.heat_smash.armed_ticks
                        st.last_event = string.format("P%d Heat Smash armed", i + 1)
                    end
                elseif not p.heat_used then
                    Engine.start_heat(st, i)
                    local heal = round_half_up(p.pool * MECH.heat.heat_start_heals_pct_of_pool / 100.0)
                    if heal > 0 and hp[i] > 0 then
                        local new_hp = math.min(p.max_hp, hp[i] + heal)
                        local gained = new_hp - hp[i]
                        if gained > 0 then
                            p.pool = p.pool - gained
                            hp[i] = new_hp
                            writes[i] = new_hp
                        end
                    end
                end
            end
            p.key_prev = down
        end
    end

    -- Rage Art stand-in: only while in Rage, once per round.
    if enabled("rage_art") and snap.art_keys ~= nil then
        for i = 0, 1 do
            local p = st.p[i]
            local down = snap.art_keys[i] == true
            if down and not p.key_prev_art and p.rage and not p.art_used and p.art_left == 0 then
                p.art_left = MECH.rage_art.armed_ticks
                p.art_used = true
                st.last_event = string.format("P%d Rage Art armed", i + 1)
            end
            p.key_prev_art = down
        end
    end

    local landed = { [0] = false, [1] = false }  -- who landed an attack this tick (hit or block)

    -- Bonus damage: any health the victim lost since last tick is scaled up by the attacker's Rage and Heat.
    for v = 0, 1 do
        local a = 1 - v
        local last = st.p[v].last_hp
        if last ~= nil and hp[v] < last then
            local drop = last - hp[v]
            landed[a] = true
            if enabled("hitstop_boost") then
                st.freeze = math.max(st.freeze or 0, MECH.hitstop_boost.boost_frames)
            end
            local mult = 1.0
            if enabled("rage") and st.p[a].rage then mult = mult * MECH.rage.damage_mult end
            if enabled("heat") and Engine.heat_active(st, a) then mult = mult * MECH.heat.damage_mult end
            if mult > 1.0 then
                local extra = math.floor(drop * (mult - 1.0) + 1e-9)  -- Tekken rounds the bonus down
                local new_hp = math.max(0, hp[v] - extra)
                if new_hp ~= hp[v] then
                    hp[v] = new_hp
                    writes[v] = new_hp
                end
            end
            -- A hit on a fighter who is not in Heat eats into their recoverable health.
            if enabled("heat") and not Engine.heat_active(st, v) and st.p[v].pool > 0 then
                local total = last - hp[v]
                local trim = round_half_up(total * MECH.heat.hit_trims_recoverable_pct / 100.0)
                st.p[v].pool = math.max(0, st.p[v].pool - trim)
            end
            -- The armed stand-in moves land on this hit.
            if enabled("heat_smash") and st.p[a].smash_left > 0 and hp[v] > 0 then
                local extra = round_half_up(st.p[v].max_hp * MECH.heat_smash.bonus_pct_of_max / 100.0)
                hp[v] = math.max(0, hp[v] - extra)
                writes[v] = hp[v]
                st.p[a].smash_left = 0
                st.p[a].heat_left = 0
                st.smash_count = st.smash_count + 1
                st.last_event = string.format("P%d Heat Smash LANDED for %d extra, Heat spent", a + 1, extra)
                if enabled("hitstop_boost") then st.freeze = math.max(st.freeze or 0, MECH.hitstop_boost.big_boost_frames) end
                if enabled("slowmo_fx") then st.fx = { scale = MECH.slowmo_fx.fx_speed_scale, frames = MECH.slowmo_fx.fx_frames } end
            end
            if enabled("rage_art") and st.p[a].art_left > 0 and hp[v] > 0 then
                local extra = round_half_up(st.p[v].max_hp * MECH.rage_art.bonus_pct_of_max / 100.0)
                hp[v] = math.max(0, hp[v] - extra)
                writes[v] = hp[v]
                st.p[v].pool = 0
                local gain = math.min(st.p[a].pool, round_half_up(st.p[a].max_hp * 0.07))
                if gain > 0 and hp[a] > 0 then
                    hp[a] = math.min(st.p[a].max_hp, hp[a] + gain)
                    st.p[a].pool = st.p[a].pool - gain
                    writes[a] = hp[a]
                end
                st.p[a].art_left = 0
                st.p[a].rage_spent = true
                st.art_count = st.art_count + 1
                st.last_event = string.format("P%d Rage Art LANDED for %d extra, Rage spent", a + 1, extra)
                if enabled("hitstop_boost") then st.freeze = math.max(st.freeze or 0, MECH.hitstop_boost.big_boost_frames) end
                if enabled("slowmo_fx") then st.fx = { scale = MECH.slowmo_fx.fx_speed_scale, frames = MECH.slowmo_fx.fx_frames } end
            end
        end
    end

    -- Blocks: an attacker whose attack was just blocked has landed an attack. In Heat it also chips the blocker:
    -- damage that cannot KO (when the sheet says so) and goes into the blocker's recoverable pool.
    for v = 0, 1 do
        local a = 1 - v
        local started_block = (snap.guard[v] or 0) > 0 and (st.p[v].last_guard or 0) == 0
        if started_block then
            landed[a] = true
            if enabled("heat") and Engine.heat_active(st, a) then
                local floor_hp = MECH.heat.chip_can_ko and 0 or 1
                if hp[v] > floor_hp then
                    local chip = st.p[v].max_hp * MECH.heat.chip_pct_of_max / 100.0
                    if enabled("rage") and st.p[v].rage then
                        chip = chip * (1.0 - MECH.rage.chip_taken_reduction_pct / 100.0)  -- Rage: 70% less chip taken
                    end
                    chip = round_half_up(chip)
                    local new_hp = math.max(floor_hp, hp[v] - chip)
                    if new_hp ~= hp[v] then
                        st.p[v].pool = st.p[v].pool + (hp[v] - new_hp)
                        hp[v] = new_hp
                        writes[v] = new_hp
                        st.chip_count = st.chip_count + 1
                    end
                end
            end
        end
    end

    -- Recoverable health: a fighter who lands an attack wins back some of what chip took from them.
    if enabled("heat") then
        for a = 0, 1 do
            local p = st.p[a]
            if landed[a] and p.pool > 0 and hp[a] > 0 then
                local want = math.min(p.pool, round_half_up(p.max_hp * MECH.heat.recover_pct_of_max_per_landed_attack / 100.0))
                local new_hp = math.min(p.max_hp, hp[a] + want)
                local gained = new_hp - hp[a]
                if gained > 0 then
                    p.pool = p.pool - gained
                    hp[a] = new_hp
                    writes[a] = new_hp
                end
            end
        end
    end

    -- Rage: at or under the threshold (and still alive).
    for i = 0, 1 do
        local p = st.p[i]
        if enabled("rage") and p.max_hp > 0 and hp[i] > 0 then
            p.rage = hp[i] <= p.max_hp * MECH.rage.hp_threshold_pct / 100.0 and not p.rage_spent
        else
            p.rage = false
        end
        if Engine.debug.force_rage[i] and enabled("rage") then p.rage = true end
        p.last_hp = hp[i]
        p.last_guard = snap.guard[i] or 0
    end

    return writes
end

-- Exposed so tests can load this file outside the game.
SF6_TEKKEN = { Engine = Engine, MECH = MECH, ROWS = ROWS }

-- ---------------------------------------------------------------------------
-- Game glue. Only runs inside REFramework.
-- ---------------------------------------------------------------------------
if re ~= nil and sdk ~= nil then
    local state = Engine.new_state()
    local last_error = nil
    local last_status = "waiting for a match"
    local stats = { writes = 0, last = "none yet", guard_now = { [0] = 0, [1] = 0 }, guard_max = { [0] = 0, [1] = 0 }, hit_now = { [0] = 0, [1] = 0 }, hit_max = { [0] = 0, [1] = 0 }, btn_now = { [0] = 0, [1] = 0 }, freeze_boosts = 0, freeze_error = nil }
    local hud = { show = true, error = nil }

    -- Settings that survive restarting the game: saved to reframework/data/sf6_tekken/settings.json.
    local SETTINGS_FILE = "sf6_tekken/settings.json"
    local SAVE_KEYS = {
        rage = { "enabled" }, heat = { "enabled" }, heat_smash = { "enabled" }, rage_art = { "enabled" },
        slowmo_fx = { "enabled", "fx_speed_scale", "fx_frames", "fx_method" },
        hitstop_boost = { "enabled", "boost_frames", "big_boost_frames" },
    }
    local LIMITS = { fx_speed_scale = { 0.1, 1.0 }, fx_frames = { 5, 120 }, boost_frames = { 0, 20 }, big_boost_frames = { 0, 40 } }
    local VALID_METHODS = { global_speed = true, scene_time_scale = true, max_fps = true }
    local DEFAULTS = {}
    for id, keys in pairs(SAVE_KEYS) do
        if MECH[id] ~= nil then
            DEFAULTS[id] = {}
            for _, k in ipairs(keys) do DEFAULTS[id][k] = MECH[id][k] end
        end
    end
    local settings = { dirty = false, note = "defaults (nothing saved yet)" }

    local function clean_value(k, v, default)
        if type(v) ~= type(default) then return nil end
        if k == "fx_method" and not VALID_METHODS[v] then return nil end
        local lim = LIMITS[k]
        if lim ~= nil then
            if v ~= v then return nil end  -- NaN
            v = math.max(lim[1], math.min(lim[2], v))
        end
        return v
    end

    local function load_settings()
        if json == nil or json.load_file == nil then return end
        local ok, data = pcall(json.load_file, SETTINGS_FILE)
        if not ok or type(data) ~= "table" then return end
        local applied = 0
        for id, keys in pairs(SAVE_KEYS) do
            local saved = data[id]
            if MECH[id] ~= nil and type(saved) == "table" then
                for _, k in ipairs(keys) do
                    local v = clean_value(k, saved[k], DEFAULTS[id][k])
                    if v ~= nil then
                        MECH[id][k] = v
                        applied = applied + 1
                    end
                end
            end
        end
        settings.note = string.format("loaded %d saved settings", applied)
    end

    local function save_settings()
        if json == nil or json.dump_file == nil then return end
        local out = {}
        for id, keys in pairs(SAVE_KEYS) do
            if MECH[id] ~= nil then
                out[id] = {}
                for _, k in ipairs(keys) do out[id][k] = MECH[id][k] end
            end
        end
        local ok, err = pcall(json.dump_file, SETTINGS_FILE, out)
        settings.note = ok and "saved" or ("save failed: " .. tostring(err))
    end

    local function reset_settings()
        for id, t in pairs(DEFAULTS) do
            for k, v in pairs(t) do MECH[id][k] = v end
        end
        settings.dirty = true
    end

    load_settings()
    local fx = { left = 0, error = nil, calls = 0, orig_fps = nil }

    -- Research readouts: live values of the fields that might be the game's hit freeze.
    local WATCH = {}
    for _, id in ipairs({ "sleep_time", "damage_sleep", "hit_stop" }) do
        for _, h in ipairs(ROWS.hooks) do
            if h.id == id then
                WATCH[#WATCH + 1] = { id = id, field = h.path_steps[#h.path_steps],
                                      now = { [0] = "n/a", [1] = "n/a" }, max = { [0] = 0, [1] = 0 } }
            end
        end
    end

    local function update_watch(players)
        for _, w in ipairs(WATCH) do
            for i = 0, 1 do
                local ok, v = pcall(function() return players[i][w.field] end)
                local n = ok and v ~= nil and tonumber(v) or nil
                if n == nil and ok and v ~= nil then n = tonumber(tostring(v)) end
                if n ~= nil then
                    w.now[i] = n
                    if n > w.max[i] then w.max[i] = n end
                else
                    w.now[i] = "n/a"
                end
            end
        end
    end

    -- Ways to slow the game. Each has apply(scale) (1.0 = normal) and restore(); either may throw if the game refuses.
    local function app_call(method, ...)
        local app = sdk.get_native_singleton("via.Application")
        local t = sdk.find_type_definition("via.Application")
        return sdk.call_native_func(app, t, method, ...)
    end

    local function current_scene()
        local sm = sdk.get_native_singleton("via.SceneManager")
        local t = sdk.find_type_definition("via.SceneManager")
        local scene = sdk.call_native_func(sm, t, "get_CurrentScene")
        if scene == nil then error("no current scene") end
        return scene
    end

    local SPEED = {
        global_speed = {
            apply = function(scale) app_call("set_GlobalSpeed", scale) end,
            restore = function() app_call("set_GlobalSpeed", 1.0) end,
        },
        scene_time_scale = {
            apply = function(scale) current_scene():call("set_TimeScale", scale) end,
            restore = function() current_scene():call("set_TimeScale", 1.0) end,
        },
        max_fps = {
            apply = function(scale)
                if fx.orig_fps == nil then
                    local cur = tonumber(app_call("get_MaxFps"))
                    if cur == nil then error("could not read the current frame cap") end
                    fx.orig_fps = cur
                end
                local base = fx.orig_fps > 0 and fx.orig_fps or 60
                app_call("set_MaxFps", math.max(5, base * scale))
            end,
            restore = function()
                if fx.orig_fps ~= nil then
                    local o = fx.orig_fps
                    fx.orig_fps = nil
                    app_call("set_MaxFps", o)
                end
            end,
        },
    }
    local METHOD_ORDER = { "global_speed", "scene_time_scale", "max_fps" }

    local function restore_speed()
        local all_ok = true
        for _, name in ipairs(METHOD_ORDER) do
            local ok = pcall(SPEED[name].restore)
            if not ok and name ~= "max_fps" then all_ok = false end
        end
        fx.left = 0
        return all_ok
    end

    local function start_fx(scale, frames)
        local method = (MECH.slowmo_fx and MECH.slowmo_fx.fx_method) or "global_speed"
        local impl = SPEED[method] or SPEED.max_fps
        local ok, err = pcall(impl.apply, scale)
        fx.calls = fx.calls + 1
        if ok then
            fx.left = frames
            fx.error = nil
        else
            fx.error = method .. ": " .. tostring(err)
            fx.left = 0
            if MECH.slowmo_fx then MECH.slowmo_fx.enabled = false end  -- the game refused it: stop trying
            restore_speed()
        end
    end

    local function num(v)
        local n = tonumber(v)
        if n ~= nil then return n end
        return tonumber(tostring(v)) or 0
    end

    local function read_snapshot()
        local t = sdk.find_type_definition("gBattle")
        if not t then return nil end
        local round = t:get_field("Round"):get_data(nil).RoundNo
        local timer = t:get_field("Game"):get_data(nil).stage_timer
        local players = t:get_field("Player"):get_data(nil).mcPlayer
        local snap = { round = num(round), timer = num(timer), hp = {}, hp_max = {}, guard = {}, hitstun = {}, buttons = {}, keys = {} }
        for i = 0, 1 do
            snap.hp[i] = num(players[i].vital_new)
            snap.guard[i] = num(players[i].guard_time)
            local ok_max, mx = pcall(function() return players[i].vital_max end)
            snap.hp_max[i] = ok_max and num(mx) or 0
            local ok_hs, hs = pcall(function() return players[i].damage_time end)
            snap.hitstun[i] = ok_hs and num(hs) or 0
            local ok_bt, bt = pcall(function() return players[i].pl_sw_now end)
            snap.buttons[i] = ok_bt and num(bt) or 0
        end
        snap.keys[0] = reframework:is_key_down(MECH.heat.key_p1) == true
        snap.keys[1] = reframework:is_key_down(MECH.heat.key_p2) == true
        if MECH.rage_art ~= nil then
            snap.art_keys = {}
            snap.art_keys[0] = reframework:is_key_down(MECH.rage_art.key_p1) == true
            snap.art_keys[1] = reframework:is_key_down(MECH.rage_art.key_p2) == true
        end
        return snap, players
    end

    local function bits(n)
        n = math.floor(n)
        local out = {}
        for k = 11, 0, -1 do out[#out + 1] = tostring(math.floor(n / 2 ^ k) % 2) end
        return table.concat(out)
    end

    -- Small on-screen readout of Heat time, Rage and recoverable health for both fighters.
    local function draw_hud()
        if not hud.show then return end
        imgui.begin_window("Tekken Heat", true, 0)
        for i = 0, 1 do
            local p = state.p[i]
            local label = string.format("P%d", i + 1)
            if Engine.heat_active(state, i) then
                local frac = p.heat_left / MECH.heat.duration_ticks
                imgui.progress_bar(frac, Vector2f.new(220, 14), string.format("%s HEAT %.1fs", label, p.heat_left / 60.0))
            elseif p.heat_used then
                imgui.text(label .. " Heat used this round")
            else
                imgui.text(label .. " Heat ready")
            end
            if p.smash_left > 0 then imgui.text(label .. " HEAT SMASH ARMED") end
            if p.art_left > 0 then imgui.text(label .. " RAGE ART ARMED") end
            if p.rage then imgui.text(label .. " RAGE") end
            if p.pool > 0 then imgui.text(string.format("%s recoverable %d", label, p.pool)) end
        end
        imgui.end_window()
    end

    re.on_frame(function()
        if settings.dirty then
            settings.dirty = false
            save_settings()
        end
        local ok, snap, players = pcall(read_snapshot)
        if not ok then
            last_error = tostring(snap)
            last_status = "could not read the match (see probe report)"
            return
        end
        if snap == nil then
            last_status = "waiting for a match"
            return
        end
        local ok2, writes = pcall(Engine.step, state, snap)
        if not ok2 then
            last_error = tostring(writes)
            return
        end
        update_watch(players)
        if state.freeze ~= nil then
            local n = state.freeze
            state.freeze = nil
            if MECH.hitstop_boost ~= nil and MECH.hitstop_boost.enabled then
                for i = 0, 1 do
                    local okf, errf = pcall(function() players[i].hit_stop = num(players[i].hit_stop) + n end)
                    if not okf then
                        stats.freeze_error = tostring(errf)
                        MECH.hitstop_boost.enabled = false  -- the game refused it: stop trying
                    end
                end
                if stats.freeze_error == nil then stats.freeze_boosts = stats.freeze_boosts + 1 end
            end
        end
        -- Slow-motion for big moments: start when the rules ask for it, always hand the speed back afterwards.
        if state.fx ~= nil then
            if MECH.slowmo_fx ~= nil and MECH.slowmo_fx.enabled then start_fx(state.fx.scale, state.fx.frames) end
            state.fx = nil
        end
        if fx.left > 0 then
            if MECH.slowmo_fx == nil or not MECH.slowmo_fx.enabled then
                restore_speed()
            else
                fx.left = fx.left - 1
                if fx.left == 0 then restore_speed() end
            end
        end
        last_status = "running (round " .. tostring(snap.round) .. ")"
        local okh, errh = pcall(draw_hud)
        hud.error = (not okh) and tostring(errh) or nil
        if not okh then hud.show = false end  -- stop retrying a readout that errors every frame
        for i = 0, 1 do
            stats.guard_now[i] = snap.guard[i]
            if snap.guard[i] > stats.guard_max[i] then stats.guard_max[i] = snap.guard[i] end
            stats.btn_now[i] = snap.buttons[i]
            stats.hit_now[i] = snap.hitstun[i]
            if snap.hitstun[i] > stats.hit_max[i] then stats.hit_max[i] = snap.hitstun[i] end
        end
        for i, new_hp in pairs(writes) do
            local before = snap.hp[i]
            local ok3, err = pcall(function() players[i].vital_new = new_hp end)
            if ok3 then
                stats.writes = stats.writes + 1
                stats.last = string.format("P%d health %d -> %d", i + 1, before, new_hp)
            else
                last_error = "health write failed: " .. tostring(err)
            end
        end
    end)

    if re.on_script_reset ~= nil then
        re.on_script_reset(function()
            restore_speed()
        end)
    end

    re.on_draw_ui(function()
        if imgui.tree_node("SF6 Tekken Mode (offline only)") then
            imgui.text("Status: " .. last_status)
            if last_error then imgui.text("Last error: " .. last_error) end
            imgui.text(string.format("Bonus health writes: %d (last: %s)", stats.writes, stats.last))
            imgui.text(string.format("Chip hits: %d   block timer now P1 %d / P2 %d, highest seen P1 %d / P2 %d",
                state.chip_count, stats.guard_now[0], stats.guard_now[1], stats.guard_max[0], stats.guard_max[1]))
            for _, id in ipairs({ "rage", "heat", "heat_smash", "rage_art", "slowmo_fx", "hitstop_boost" }) do
                if MECH[id] ~= nil then
                    local changed, value = imgui.checkbox(id .. " enabled", MECH[id].enabled)
                    if changed then
                        MECH[id].enabled = value
                        settings.dirty = true
                    end
                end
            end
            imgui.text(string.format("Heat Smashes landed: %d   Rage Arts landed: %d", state.smash_count, state.art_count))
            imgui.text(string.format("Hitstun timer now P1 %d / P2 %d, highest seen P1 %d / P2 %d",
                stats.hit_now[0], stats.hit_now[1], stats.hit_max[0], stats.hit_max[1]))
            for _, w in ipairs(WATCH) do
                imgui.text(string.format("Hit-freeze candidate %s: now P1 %s / P2 %s, highest seen P1 %s / P2 %s",
                    w.field, tostring(w.now[0]), tostring(w.now[1]), tostring(w.max[0]), tostring(w.max[1])))
            end
            imgui.text(string.format("Held buttons (game bits) P1 %d [%s]  P2 %d [%s]",
                stats.btn_now[0], bits(stats.btn_now[0]), stats.btn_now[1], bits(stats.btn_now[1])))
            local hchanged, hvalue = imgui.checkbox("show on-screen Heat / Rage readout", hud.show)
            if hchanged then hud.show = hvalue; hud.error = nil end
            if hud.error then imgui.text("On-screen readout error: " .. hud.error) end
            imgui.text("Last Heat event: " .. state.last_event)
            imgui.text("Settings: " .. settings.note)
            if imgui.button("reset settings to defaults") then reset_settings() end
            imgui.text("Debug (for testing only):")
            local fchanged, fvalue = imgui.checkbox("force P1 Rage on", Engine.debug.force_rage[0])
            if fchanged then Engine.debug.force_rage[0] = fvalue end
            if imgui.button("start P1 Heat now (no key)") then Engine.start_heat(state, 0) end
            if imgui.button("arm P1 Heat Smash (needs Heat on)") then Engine.arm_smash(state, 0) end
            if imgui.button("arm P1 Rage Art (no key)") then Engine.arm_art(state, 0) end
            if MECH.slowmo_fx ~= nil and imgui.button("test slow-motion now (about 1 second)") then
                start_fx(MECH.slowmo_fx.fx_speed_scale, MECH.slowmo_fx.fx_frames)
            end
            if MECH.slowmo_fx ~= nil then
                imgui.text("Slow-motion method: " .. tostring(MECH.slowmo_fx.fx_method))
                for _, name in ipairs(METHOD_ORDER) do
                    if imgui.button("use method: " .. name) then
                        MECH.slowmo_fx.fx_method = name
                        settings.dirty = true
                        fx.error = nil
                    end
                end
            end
            if MECH.slowmo_fx ~= nil then
                pcall(function()
                    local c1, v1 = imgui.slider_float("slow-motion speed (1.0 = normal)", MECH.slowmo_fx.fx_speed_scale, 0.1, 1.0)
                    if c1 then MECH.slowmo_fx.fx_speed_scale = v1; settings.dirty = true end
                    local c2, v2 = imgui.slider_int("slow-motion length (frames)", MECH.slowmo_fx.fx_frames, 5, 120)
                    if c2 then MECH.slowmo_fx.fx_frames = v2; settings.dirty = true end
                end)
            end
            if MECH.hitstop_boost ~= nil then
                pcall(function()
                    local c3, v3 = imgui.slider_int("hit freeze boost (frames)", MECH.hitstop_boost.boost_frames, 0, 20)
                    if c3 then MECH.hitstop_boost.boost_frames = v3; settings.dirty = true end
                    local c4, v4 = imgui.slider_int("big hit freeze boost (frames)", MECH.hitstop_boost.big_boost_frames, 0, 40)
                    if c4 then MECH.hitstop_boost.big_boost_frames = v4; settings.dirty = true end
                end)
                imgui.text(string.format("Hit freeze boosts applied: %d", stats.freeze_boosts))
                if stats.freeze_error then imgui.text("Hit freeze error: " .. stats.freeze_error) end
            end
            if fx.error then imgui.text("Slow-motion error: " .. fx.error) end
            imgui.text(string.format("Slow-motion calls made: %d", fx.calls))
            for i = 0, 1 do
                imgui.text(string.format("P%d  rage: %s  heat: %s (%d ticks left, available this round: %s)  recoverable: %d", i + 1,
                    tostring(state.p[i].rage), tostring(Engine.heat_active(state, i)),
                    Engine.heat_left(state, i), tostring(Engine.heat_available(state, i)), state.p[i].pool))
            end
            imgui.tree_pop()
        end
    end)
end
