-- SF6 Tekken Mode: Rage and Heat for Street Fighter 6, OFFLINE play only.
-- GENERATED by tools/build.py from sheets/*.json. Do not edit this file: change the sheets or src/engine.lua.tpl.
-- Status: not yet run in the real game. Field names are unproven until sf6_tekken_probe.lua says otherwise.

--@@ROWS@@

local MECH = {}
for _, r in ipairs(ROWS.mechanics) do MECH[r.id] = r end

-- ---------------------------------------------------------------------------
-- Rules. Pure logic: takes a snapshot of the match, returns the health writes
-- to make. No game calls in here, so it can be tested without the game.
--   snap = { round = n, timer = n, hp = {[0]=n,[1]=n}, hp_max = {[0]=n,[1]=n} (optional), guard = {[0]=n,[1]=n}, hitstun = {[0]=n,[1]=n} (optional), keys = {[0]=bool,[1]=bool} }
-- ---------------------------------------------------------------------------
local Engine = {}

local function new_player()
    return { max_hp = 0, last_hp = nil, last_guard = 0, rage = false, key_prev = false,
             heat_left = 0, heat_used = false, heat_paused = 0, heat_ran = 0, pool = 0 }
end

function Engine.new_state()
    return { round = nil, last_timer = nil, tick = 0, chip_count = 0, last_event = "none yet", p = { [0] = new_player(), [1] = new_player() } }
end

local function enabled(id)
    local r = MECH[id]
    return r ~= nil and r.enabled == true
end

local function round_half_up(x)
    return math.floor(x + 0.5)
end

-- Debug switches for testing in the real game without having to get low on health or press the key.
Engine.debug = { force_rage = { [0] = false, [1] = false } }

-- Heat (Tekken 8): once per round, a timer that only runs while the opponent is not in hitstun.
function Engine.start_heat(st, i)
    local p = st.p[i]
    p.heat_left = MECH.heat.duration_ticks
    p.heat_used = true
    p.heat_paused = 0
    p.heat_ran = 0
end

function Engine.heat_active(st, i)
    return st.p[i].heat_left > 0
end

function Engine.heat_left(st, i)
    return st.p[i].heat_left
end

function Engine.heat_available(st, i)
    return not st.p[i].heat_used
end

-- Returns a table { [playerIndex] = newHealth } for every health write to make this call.
function Engine.step(st, snap)
    local writes = {}

    -- A new round: the game's round number changed, OR the match timer jumped backwards
    -- (probe screenshots showed the round number reading 0 in a later round, so it can't be relied on alone).
    local timer_jumped_back = st.last_timer ~= nil and snap.timer < st.last_timer - 30
    local was_heat = { [0] = Engine.heat_active(st, 0), [1] = Engine.heat_active(st, 1) }
    if snap.round ~= st.round or timer_jumped_back then
        for i = 0, 1 do
            if was_heat[i] then
                st.last_event = string.format("P%d Heat CLEARED by a reset: timer %s -> %s, round %s -> %s",
                    i + 1, tostring(st.last_timer), tostring(snap.timer), tostring(st.round), tostring(snap.round))
            end
        end
        st.round = snap.round
        st.last_timer = nil
        st.tick = 0
        st.p = { [0] = new_player(), [1] = new_player() }
    end

    if snap.timer == st.last_timer then return writes end
    st.last_timer = snap.timer
    st.tick = st.tick + 1

    -- Heat timer: runs only while the opponent is not in hitstun (when the sheet says so).
    if enabled("heat") then
        for i = 0, 1 do
            local p = st.p[i]
            if p.heat_left > 0 then
                local stunned = snap.hitstun ~= nil and (snap.hitstun[1 - i] or 0) > 0
                if MECH.heat.pause_while_opponent_in_hitstun and stunned then
                    p.heat_paused = p.heat_paused + 1
                else
                    p.heat_left = p.heat_left - 1
                    p.heat_ran = p.heat_ran + 1
                    if p.heat_left == 0 then
                        st.last_event = string.format("P%d Heat ended: timer ran out after %d running ticks (paused %d ticks while the opponent was hit)",
                            i + 1, p.heat_ran, p.heat_paused)
                    end
                end
            end
        end
    end

    local hp = { [0] = snap.hp[0], [1] = snap.hp[1] }
    for i = 0, 1 do
        local real_max = snap.hp_max ~= nil and snap.hp_max[i] or nil
        if real_max ~= nil and real_max > 0 then
            st.p[i].max_hp = real_max
        elseif hp[i] > st.p[i].max_hp then
            st.p[i].max_hp = hp[i]  -- fallback: highest health seen this round
        end
    end

    -- Heat: a key press starts it, once per round (a new round, or a timer reset, gives it back).
    if enabled("heat") then
        for i = 0, 1 do
            local p = st.p[i]
            local down = snap.keys[i] == true
            if down and not p.key_prev and not p.heat_used and not Engine.heat_active(st, i) then
                Engine.start_heat(st, i)
            end
            p.key_prev = down
        end
    end

    local landed = { [0] = false, [1] = false }  -- who landed an attack this tick (hit or block)

    -- Bonus damage: any health the victim lost since last tick is scaled up by the attacker's Rage and Heat.
    for v = 0, 1 do
        local a = 1 - v
        local last = st.p[v].last_hp
        if last ~= nil and hp[v] < last then
            local drop = last - hp[v]
            landed[a] = true
            local mult = 1.0
            if enabled("rage") and st.p[a].rage then mult = mult * MECH.rage.damage_mult end
            if enabled("heat") and Engine.heat_active(st, a) then mult = mult * MECH.heat.damage_mult end
            if mult > 1.0 then
                local extra = math.floor(drop * (mult - 1.0) + 1e-9)  -- Tekken rounds the bonus down
                local new_hp = math.max(0, hp[v] - extra)
                if new_hp ~= hp[v] then
                    hp[v] = new_hp
                    writes[v] = new_hp
                end
            end
            -- A hit on a fighter who is not in Heat eats into their recoverable health.
            if enabled("heat") and not Engine.heat_active(st, v) and st.p[v].pool > 0 then
                local total = last - hp[v]
                local trim = round_half_up(total * MECH.heat.hit_trims_recoverable_pct / 100.0)
                st.p[v].pool = math.max(0, st.p[v].pool - trim)
            end
        end
    end

    -- Blocks: an attacker whose attack was just blocked has landed an attack. In Heat it also chips the blocker:
    -- damage that cannot KO (when the sheet says so) and goes into the blocker's recoverable pool.
    for v = 0, 1 do
        local a = 1 - v
        local started_block = (snap.guard[v] or 0) > 0 and (st.p[v].last_guard or 0) == 0
        if started_block then
            landed[a] = true
            if enabled("heat") and Engine.heat_active(st, a) then
                local floor_hp = MECH.heat.chip_can_ko and 0 or 1
                if hp[v] > floor_hp then
                    local chip = st.p[v].max_hp * MECH.heat.chip_pct_of_max / 100.0
                    if enabled("rage") and st.p[v].rage then
                        chip = chip * (1.0 - MECH.rage.chip_taken_reduction_pct / 100.0)  -- Rage: 70% less chip taken
                    end
                    chip = round_half_up(chip)
                    local new_hp = math.max(floor_hp, hp[v] - chip)
                    if new_hp ~= hp[v] then
                        st.p[v].pool = st.p[v].pool + (hp[v] - new_hp)
                        hp[v] = new_hp
                        writes[v] = new_hp
                        st.chip_count = st.chip_count + 1
                    end
                end
            end
        end
    end

    -- Recoverable health: a fighter who lands an attack wins back some of what chip took from them.
    if enabled("heat") then
        for a = 0, 1 do
            local p = st.p[a]
            if landed[a] and p.pool > 0 and hp[a] > 0 then
                local want = math.min(p.pool, round_half_up(p.max_hp * MECH.heat.recover_pct_of_max_per_landed_attack / 100.0))
                local new_hp = math.min(p.max_hp, hp[a] + want)
                local gained = new_hp - hp[a]
                if gained > 0 then
                    p.pool = p.pool - gained
                    hp[a] = new_hp
                    writes[a] = new_hp
                end
            end
        end
    end

    -- Rage: at or under the threshold (and still alive).
    for i = 0, 1 do
        local p = st.p[i]
        if enabled("rage") and p.max_hp > 0 and hp[i] > 0 then
            p.rage = hp[i] <= p.max_hp * MECH.rage.hp_threshold_pct / 100.0
        else
            p.rage = false
        end
        if Engine.debug.force_rage[i] and enabled("rage") then p.rage = true end
        p.last_hp = hp[i]
        p.last_guard = snap.guard[i] or 0
    end

    return writes
end

-- Exposed so tests can load this file outside the game.
SF6_TEKKEN = { Engine = Engine, MECH = MECH, ROWS = ROWS }

-- ---------------------------------------------------------------------------
-- Game glue. Only runs inside REFramework.
-- ---------------------------------------------------------------------------
if re ~= nil and sdk ~= nil then
    local state = Engine.new_state()
    local last_error = nil
    local last_status = "waiting for a match"
    local stats = { writes = 0, last = "none yet", guard_now = { [0] = 0, [1] = 0 }, guard_max = { [0] = 0, [1] = 0 }, hit_now = { [0] = 0, [1] = 0 }, hit_max = { [0] = 0, [1] = 0 }, btn_now = { [0] = 0, [1] = 0 } }
    local hud = { show = true, error = nil }

    local function num(v)
        local n = tonumber(v)
        if n ~= nil then return n end
        return tonumber(tostring(v)) or 0
    end

    local function read_snapshot()
        local t = sdk.find_type_definition("gBattle")
        if not t then return nil end
        local round = t:get_field("Round"):get_data(nil).RoundNo
        local timer = t:get_field("Game"):get_data(nil).stage_timer
        local players = t:get_field("Player"):get_data(nil).mcPlayer
        local snap = { round = num(round), timer = num(timer), hp = {}, hp_max = {}, guard = {}, hitstun = {}, buttons = {}, keys = {} }
        for i = 0, 1 do
            snap.hp[i] = num(players[i].vital_new)
            snap.guard[i] = num(players[i].guard_time)
            local ok_max, mx = pcall(function() return players[i].vital_max end)
            snap.hp_max[i] = ok_max and num(mx) or 0
            local ok_hs, hs = pcall(function() return players[i].damage_time end)
            snap.hitstun[i] = ok_hs and num(hs) or 0
            local ok_bt, bt = pcall(function() return players[i].pl_sw_now end)
            snap.buttons[i] = ok_bt and num(bt) or 0
        end
        snap.keys[0] = reframework:is_key_down(MECH.heat.key_p1) == true
        snap.keys[1] = reframework:is_key_down(MECH.heat.key_p2) == true
        return snap, players
    end

    local function bits(n)
        n = math.floor(n)
        local out = {}
        for k = 11, 0, -1 do out[#out + 1] = tostring(math.floor(n / 2 ^ k) % 2) end
        return table.concat(out)
    end

    -- Small on-screen readout of Heat time, Rage and recoverable health for both fighters.
    local function draw_hud()
        if not hud.show then return end
        imgui.begin_window("Tekken Heat", true, 0)
        for i = 0, 1 do
            local p = state.p[i]
            local label = string.format("P%d", i + 1)
            if Engine.heat_active(state, i) then
                local frac = p.heat_left / MECH.heat.duration_ticks
                imgui.progress_bar(frac, Vector2f.new(220, 14), string.format("%s HEAT %.1fs", label, p.heat_left / 60.0))
            elseif p.heat_used then
                imgui.text(label .. " Heat used this round")
            else
                imgui.text(label .. " Heat ready")
            end
            if p.rage then imgui.text(label .. " RAGE") end
            if p.pool > 0 then imgui.text(string.format("%s recoverable %d", label, p.pool)) end
        end
        imgui.end_window()
    end

    re.on_frame(function()
        local ok, snap, players = pcall(read_snapshot)
        if not ok then
            last_error = tostring(snap)
            last_status = "could not read the match (see probe report)"
            return
        end
        if snap == nil then
            last_status = "waiting for a match"
            return
        end
        local ok2, writes = pcall(Engine.step, state, snap)
        if not ok2 then
            last_error = tostring(writes)
            return
        end
        last_status = "running (round " .. tostring(snap.round) .. ")"
        local okh, errh = pcall(draw_hud)
        hud.error = (not okh) and tostring(errh) or nil
        if not okh then hud.show = false end  -- stop retrying a readout that errors every frame
        for i = 0, 1 do
            stats.guard_now[i] = snap.guard[i]
            if snap.guard[i] > stats.guard_max[i] then stats.guard_max[i] = snap.guard[i] end
            stats.btn_now[i] = snap.buttons[i]
            stats.hit_now[i] = snap.hitstun[i]
            if snap.hitstun[i] > stats.hit_max[i] then stats.hit_max[i] = snap.hitstun[i] end
        end
        for i, new_hp in pairs(writes) do
            local before = snap.hp[i]
            local ok3, err = pcall(function() players[i].vital_new = new_hp end)
            if ok3 then
                stats.writes = stats.writes + 1
                stats.last = string.format("P%d health %d -> %d", i + 1, before, new_hp)
            else
                last_error = "health write failed: " .. tostring(err)
            end
        end
    end)

    re.on_draw_ui(function()
        if imgui.tree_node("SF6 Tekken Mode (offline only)") then
            imgui.text("Status: " .. last_status)
            if last_error then imgui.text("Last error: " .. last_error) end
            imgui.text(string.format("Bonus health writes: %d (last: %s)", stats.writes, stats.last))
            imgui.text(string.format("Chip hits: %d   block timer now P1 %d / P2 %d, highest seen P1 %d / P2 %d",
                state.chip_count, stats.guard_now[0], stats.guard_now[1], stats.guard_max[0], stats.guard_max[1]))
            for _, id in ipairs({ "rage", "heat" }) do
                local changed, value = imgui.checkbox(id .. " enabled", MECH[id].enabled)
                if changed then MECH[id].enabled = value end
            end
            imgui.text(string.format("Hitstun timer now P1 %d / P2 %d, highest seen P1 %d / P2 %d",
                stats.hit_now[0], stats.hit_now[1], stats.hit_max[0], stats.hit_max[1]))
            imgui.text(string.format("Held buttons (game bits) P1 %d [%s]  P2 %d [%s]",
                stats.btn_now[0], bits(stats.btn_now[0]), stats.btn_now[1], bits(stats.btn_now[1])))
            local hchanged, hvalue = imgui.checkbox("show on-screen Heat / Rage readout", hud.show)
            if hchanged then hud.show = hvalue; hud.error = nil end
            if hud.error then imgui.text("On-screen readout error: " .. hud.error) end
            imgui.text("Last Heat event: " .. state.last_event)
            imgui.text("Debug (for testing only):")
            local fchanged, fvalue = imgui.checkbox("force P1 Rage on", Engine.debug.force_rage[0])
            if fchanged then Engine.debug.force_rage[0] = fvalue end
            if imgui.button("start P1 Heat now (no key)") then Engine.start_heat(state, 0) end
            for i = 0, 1 do
                imgui.text(string.format("P%d  rage: %s  heat: %s (%d ticks left, available this round: %s)  recoverable: %d", i + 1,
                    tostring(state.p[i].rage), tostring(Engine.heat_active(state, i)),
                    Engine.heat_left(state, i), tostring(Engine.heat_available(state, i)), state.p[i].pool))
            end
            imgui.tree_pop()
        end
    end)
end
