-- SF6 Tekken Mode: Rage and Heat for Street Fighter 6, OFFLINE play only.
-- GENERATED by tools/build.py from sheets/*.json. Do not edit this file: change the sheets or src/engine.lua.tpl.
-- Status: not yet run in the real game. Field names are unproven until sf6_tekken_probe.lua says otherwise.

--@@ROWS@@

local MECH = {}
for _, r in ipairs(ROWS.mechanics) do MECH[r.id] = r end

-- ---------------------------------------------------------------------------
-- Rules. Pure logic: takes a snapshot of the match, returns the health writes
-- to make. No game calls in here, so it can be tested without the game.
--   snap = { round = n, timer = n, hp = {[0]=n,[1]=n}, hp_max = {[0]=n,[1]=n} (optional), guard = {[0]=n,[1]=n}, keys = {[0]=bool,[1]=bool} }
-- ---------------------------------------------------------------------------
local Engine = {}

local function new_player()
    return { max_hp = 0, last_hp = nil, last_guard = 0, rage = false, heat_until = 0, heat_ready_at = 0, key_prev = false }
end

function Engine.new_state()
    return { round = nil, last_timer = nil, tick = 0, p = { [0] = new_player(), [1] = new_player() } }
end

local function enabled(id)
    local r = MECH[id]
    return r ~= nil and r.enabled == true
end

local function round_half_up(x)
    return math.floor(x + 0.5)
end

-- Debug switches for testing in the real game without having to get low on health or press the key.
Engine.debug = { force_rage = { [0] = false, [1] = false } }

function Engine.start_heat(st, i)
    local p = st.p[i]
    local heat = MECH.heat
    p.heat_until = st.tick + heat.duration_ticks
    p.heat_ready_at = p.heat_until + heat.cooldown_ticks
end

function Engine.heat_active(st, i)
    return st.tick < st.p[i].heat_until
end

-- Returns a table { [playerIndex] = newHealth } for every health write to make this call.
function Engine.step(st, snap)
    local writes = {}

    -- A new round: the game's round number changed, OR the match timer jumped backwards
    -- (probe screenshots showed the round number reading 0 in a later round, so it can't be relied on alone).
    local timer_jumped_back = st.last_timer ~= nil and snap.timer < st.last_timer - 30
    if snap.round ~= st.round or timer_jumped_back then
        st.round = snap.round
        st.last_timer = nil
        st.tick = 0
        st.p = { [0] = new_player(), [1] = new_player() }
    end

    if snap.timer == st.last_timer then return writes end
    st.last_timer = snap.timer
    st.tick = st.tick + 1

    local hp = { [0] = snap.hp[0], [1] = snap.hp[1] }
    for i = 0, 1 do
        local real_max = snap.hp_max ~= nil and snap.hp_max[i] or nil
        if real_max ~= nil and real_max > 0 then
            st.p[i].max_hp = real_max
        elseif hp[i] > st.p[i].max_hp then
            st.p[i].max_hp = hp[i]  -- fallback: highest health seen this round
        end
    end

    -- Heat: key press starts a timed burst, then a cooldown.
    if enabled("heat") then
        local heat = MECH.heat
        for i = 0, 1 do
            local p = st.p[i]
            local down = snap.keys[i] == true
            if down and not p.key_prev and st.tick >= p.heat_ready_at and not Engine.heat_active(st, i) then
                Engine.start_heat(st, i)
            end
            p.key_prev = down
        end
    end

    -- Bonus damage: any health the victim lost since last tick is scaled up by the attacker's Rage and Heat.
    for v = 0, 1 do
        local a = 1 - v
        local last = st.p[v].last_hp
        if last ~= nil and hp[v] < last then
            local drop = last - hp[v]
            local mult = 1.0
            if enabled("rage") and st.p[a].rage then mult = mult * MECH.rage.damage_mult end
            if enabled("heat") and Engine.heat_active(st, a) then mult = mult * MECH.heat.damage_mult end
            if mult > 1.0 then
                local extra = round_half_up(drop * (mult - 1.0))
                local new_hp = math.max(0, hp[v] - extra)
                if new_hp ~= hp[v] then
                    hp[v] = new_hp
                    writes[v] = new_hp
                end
            end
        end
    end

    -- Chip damage: a fighter who starts blocking while the attacker is in Heat loses a slice of max health (never the last point).
    if enabled("heat") then
        for v = 0, 1 do
            local a = 1 - v
            local started_block = (snap.guard[v] or 0) > 0 and (st.p[v].last_guard or 0) == 0
            if started_block and Engine.heat_active(st, a) and hp[v] > 1 then
                local chip = round_half_up(st.p[v].max_hp * MECH.heat.chip_pct_of_max / 100.0)
                local new_hp = math.max(1, hp[v] - chip)
                if new_hp ~= hp[v] then
                    hp[v] = new_hp
                    writes[v] = new_hp
                end
            end
        end
    end

    -- Rage: at or under the threshold (and still alive).
    for i = 0, 1 do
        local p = st.p[i]
        if enabled("rage") and p.max_hp > 0 and hp[i] > 0 then
            p.rage = hp[i] <= p.max_hp * MECH.rage.hp_threshold_pct / 100.0
        else
            p.rage = false
        end
        if Engine.debug.force_rage[i] and enabled("rage") then p.rage = true end
        p.last_hp = hp[i]
        p.last_guard = snap.guard[i] or 0
    end

    return writes
end

-- Exposed so tests can load this file outside the game.
SF6_TEKKEN = { Engine = Engine, MECH = MECH, ROWS = ROWS }

-- ---------------------------------------------------------------------------
-- Game glue. Only runs inside REFramework.
-- ---------------------------------------------------------------------------
if re ~= nil and sdk ~= nil then
    local state = Engine.new_state()
    local last_error = nil
    local last_status = "waiting for a match"
    local stats = { writes = 0, last = "none yet" }

    local function num(v)
        local n = tonumber(v)
        if n ~= nil then return n end
        return tonumber(tostring(v)) or 0
    end

    local function read_snapshot()
        local t = sdk.find_type_definition("gBattle")
        if not t then return nil end
        local round = t:get_field("Round"):get_data(nil).RoundNo
        local timer = t:get_field("Game"):get_data(nil).stage_timer
        local players = t:get_field("Player"):get_data(nil).mcPlayer
        local snap = { round = num(round), timer = num(timer), hp = {}, hp_max = {}, guard = {}, keys = {} }
        for i = 0, 1 do
            snap.hp[i] = num(players[i].vital_new)
            snap.guard[i] = num(players[i].guard_time)
            local ok_max, mx = pcall(function() return players[i].vital_max end)
            snap.hp_max[i] = ok_max and num(mx) or 0
        end
        snap.keys[0] = reframework:is_key_down(MECH.heat.key_p1) == true
        snap.keys[1] = reframework:is_key_down(MECH.heat.key_p2) == true
        return snap, players
    end

    re.on_frame(function()
        local ok, snap, players = pcall(read_snapshot)
        if not ok then
            last_error = tostring(snap)
            last_status = "could not read the match (see probe report)"
            return
        end
        if snap == nil then
            last_status = "waiting for a match"
            return
        end
        local ok2, writes = pcall(Engine.step, state, snap)
        if not ok2 then
            last_error = tostring(writes)
            return
        end
        last_status = "running (round " .. tostring(snap.round) .. ")"
        for i, new_hp in pairs(writes) do
            local before = snap.hp[i]
            local ok3, err = pcall(function() players[i].vital_new = new_hp end)
            if ok3 then
                stats.writes = stats.writes + 1
                stats.last = string.format("P%d health %d -> %d", i + 1, before, new_hp)
            else
                last_error = "health write failed: " .. tostring(err)
            end
        end
    end)

    re.on_draw_ui(function()
        if imgui.tree_node("SF6 Tekken Mode (offline only)") then
            imgui.text("Status: " .. last_status)
            if last_error then imgui.text("Last error: " .. last_error) end
            imgui.text(string.format("Bonus health writes: %d (last: %s)", stats.writes, stats.last))
            for _, id in ipairs({ "rage", "heat" }) do
                local changed, value = imgui.checkbox(id .. " enabled", MECH[id].enabled)
                if changed then MECH[id].enabled = value end
            end
            imgui.text("Debug (for testing only):")
            local fchanged, fvalue = imgui.checkbox("force P1 Rage on", Engine.debug.force_rage[0])
            if fchanged then Engine.debug.force_rage[0] = fvalue end
            if imgui.button("start P1 Heat now (no key)") then Engine.start_heat(state, 0) end
            for i = 0, 1 do
                imgui.text(string.format("P%d  rage: %s  heat: %s", i + 1,
                    tostring(state.p[i].rage), tostring(Engine.heat_active(state, i))))
            end
            imgui.tree_pop()
        end
    end)
end
